### ISSUE TITLE
ToleranceTable and TableTopVerticalPosition

### ISSUE THREAD

**Issue by Kiragroh** [x2sky/Esapi_AddSetupBeams#1]
Hi x2sky,

I implemented your code in my script and all works fine.

Could you overcome this two limitations of ESAPI:
- selecting ToleranceTable automatically (no ESAPI-access)
- changing TableTopVerticalPosition to 0 (read only)

**Comment by x2sky** [comment]
Max,

Tolerance table is get only and it is directly under beam properties so I don't see a possible way to resolve that.
Table position is under editableparameters, so a potential workaround is to copy editableparameters from another fixed beam with the desirable table positions, edit the editable parameters so that it fits the setup beam... I don't know if this workaround will work, but the condition is extremely limited so I don't think it is worth the time to even try. In short, I don't see a way to edit table position.
The best way is to wait for the next update.
---

Becket Hui
________________________________

**Comment by Kiragroh** [comment]
Thanks for the reply but sadly these were my thoughts too. Till the next update.^^
